name: Fetch xkcd json

on:
  #  schedule:
  #    - cron: "0 5 * * *" # Runs daily
  workflow_dispatch:

jobs:
  fetch_json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install_tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: get_json
        run: bash fetch_json.sh

      - name: generate_xml
        run: bash generate_rss.sh

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

          git add .
          git commit -m "Fetch new episodes" || echo "No changes to commit"

          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
